type: discrete
extra_features: null
transition: 'uniform'
model: 'graph_tf'
diffusion_steps: 1000
diffusion_noise_schedule: 'cosine'
n_layers: 5

hidden_mlp_dims: {'X': 32, 'E': 32, 'y': 32}
hidden_dims: {'dx': 32, 'de': 32, 'dy': 32, 'n_head': 4, 'dim_ffX': 32, 'dim_ffE': 32, 'dim_ffy': 32}

lambda_train: [5, 0]
